# 📊 Notebook 1: Load & Explore Data dengan Pandas

**Topik:** Importing Data, Inspeksi Tipe Data, Seleksi Kolom, Sorting

**Dataset:** EPL Goal Scorer 2020-2021 (dibuat secara lokal agar eksperimen bisa dijalankan offline)

---

## 1. Import Library

In [4]:
import pandas as pd
import numpy as np

print('✅ Library berhasil di-import!')
print(f'Pandas version  : {pd.__version__}')
print(f'NumPy  version  : {np.__version__}')

✅ Library berhasil di-import!
Pandas version  : 2.3.3
NumPy  version  : 2.2.5

## 2. Membuat Dataset EPL Goal Scorer (Simulasi)

Dataset ini merepresentasikan data pencetak gol EPL musim 2020-2021 seperti yang digunakan di materi.

In [5]:
# Membuat data sample EPL Goal Scorer 2020-21
np.random.seed(42)
n_players = 50

players = [
    'Harry Kane', 'Mohamed Salah', 'Bruno Fernandes', 'Son Heung-Min',
    'Patrick Bamford', 'Dominic Calvert-Lewin', 'Jamie Vardy', 'Ollie Watkins',
    'Ilkay Gündogan', 'Alexandre Lacazette', 'Callum Wilson', 'Danny Ings',
    'Marcus Rashford', 'Sadio Mané', 'Gareth Bale', 'Phil Foden',
    'Kevin De Bruyne', 'Jack Grealish', 'Mason Greenwood', 'Timo Werner',
    'Pierre-Emerick Aubameyang', 'Raheem Sterling', 'Jesse Lingard',
    'Riyad Mahrez', 'Harvey Barnes', 'Diogo Jota', 'Gabriel Jesus',
    'Stuart Dallas', 'Neal Maupay', 'Nicolas Pepe',
    'Jarrod Bowen', 'Bertrand Traoré', 'Jorginho', 'Rodrigo',
    'Richarlison', 'Ferrán Torres', 'Tammy Abraham', 'Gylfi Sigurdsson',
    'Danny Welbeck', 'Joe Wilcock', 'James Maddison', 'Jack Harrison',
    'Roberto Firmino', 'Anwar El Ghazi', 'Tomas Soucek', 'Edinson Cavani',
    'Che Adams', 'James Ward-Prowse', 'Michail Antonio', 'Christian Benteke'
]

teams = [
    'Tottenham', 'Liverpool', 'Manchester United', 'Tottenham',
    'Leeds', 'Everton', 'Leicester', 'Aston Villa',
    'Manchester City', 'Arsenal', 'Newcastle United', 'Southampton',
    'Manchester United', 'Liverpool', 'Tottenham', 'Manchester City',
    'Manchester City', 'Aston Villa', 'Manchester United', 'Chelsea',
    'Arsenal', 'Manchester City', 'Manchester United',
    'Manchester City', 'Leicester', 'Liverpool', 'Manchester City',
    'Leeds', 'Brighton', 'Arsenal',
    'West Ham', 'Aston Villa', 'Chelsea', 'Leeds',
    'Everton', 'Manchester City', 'Chelsea', 'Everton',
    'Brighton', 'Crystal Palace', 'Leicester', 'Leeds',
    'Liverpool', 'Aston Villa', 'West Ham', 'Manchester United',
    'Southampton', 'Southampton', 'West Ham', 'Crystal Palace'
]

goals = [23,22,18,17,17,16,15,14,13,13,12,12,11,11,11,9,6,6,7,6,10,10,9,9,9,9,8,8,8,8,8,7,7,7,7,7,6,6,6,8,8,8,9,10,10,10,9,8,10,10]
games = [35,37,37,37,38,35,34,37,28,29,16,28,37,34,20,28,24,26,24,35,29,33,26,33,34,30,26,37,29,33,26,30,28,29,35,25,28,29,28,25,28,32,33,28,37,26,31,35,28,29]
assists = [14,5,12,10,7,4,4,4,7,4,1,4,11,7,3,5,11,10,3,4,3,5,4,5,4,4,4,2,5,3,4,2,2,2,2,2,3,3,3,1,4,3,1,2,3,1,2,2,4,1]
positions = ['F','F','M','F','F','F','F','F','M','F','F','F','F','F','F','M','M','F M S','F','F','F','M S','M','M S','F M S','F','F','D M S','F M S','M S','F M S','F M S','D M S','F M S','F M S','F M S','F','M S','F','M S','M S','D','F','F','M S','F','F','D M S','F','F']
shots = [138,76,121,68,82,67,80,79,50,22,50,69,70,68,41,28,79,50,40,80,50,44,35,56,60,58,52,26,48,58,44,32,26,30,48,40,45,36,28,44,40,38,54,48,58,38,32,28,40,34]
xg = [22.17,20.25,16.02,11.02,18.40,15.50,19.94,13.50,5.97,3.56,8.50,14.60,9.80,10.24,12.70,6.50,9.91,5.19,7.20,13.43,10.30,8.44,6.80,9.50,10.40,8.60,7.80,5.10,7.50,7.20,5.80,4.20,3.80,4.00,6.80,4.00,5.20,4.10,3.80,4.80,4.20,3.50,7.00,6.50,7.80,5.40,5.20,4.80,6.40,5.80]

df = pd.DataFrame({
    'player_name': players,
    'team_title': teams,
    'position': positions,
    'games': games,
    'goals': goals,
    'assists': assists,
    'shots': shots,
    'xG': xg,
    'yellow_cards': np.random.randint(0, 8, n_players),
    'red_cards': np.random.randint(0, 2, n_players),
    'key_passes': np.random.randint(5, 80, n_players),
})

# Simpan ke CSV (simulasi file lokal)
df.to_csv('epl_goalscorer_2021.csv', index=False)
print(f'✅ Dataset dibuat! Shape: {df.shape}')

✅ Dataset dibuat! Shape: (50, 11)

## 3. Import CSV ke Pandas DataFrame

Sesuai materi: **Importing Data to Pandas** menggunakan `pd.read_csv()`

In [6]:
path = 'epl_goalscorer_2021.csv'
df = pd.read_csv(path)

print(f'Jumlah baris  : {df.shape[0]}')
print(f'Jumlah kolom  : {df.shape[1]}')
df

Jumlah baris  : 50
Jumlah kolom  : 11

,player_name,team_title,position,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
0,Harry Kane,Tottenham,F,35,23,14,138,22.17,6,0,67
1,Mohamed Salah,Liverpool,F,37,22,5,76,20.25,3,1,22
2,Bruno Fernandes,Manchester United,M,37,18,12,121,16.02,4,0,48
3,Son Heung-Min,Tottenham,F,37,17,10,68,11.02,6,1,38
4,Patrick Bamford,Leeds,F,38,17,7,82,18.40,2,0,78
5,Dominic Calvert-Lewin,Everton,F,35,16,4,67,15.50,7,1,66
6,Jamie Vardy,Leicester,F,34,15,4,80,19.94,4,1,18
7,Ollie Watkins,Aston Villa,F,37,14,4,79,13.50,4,0,52
8,Ilkay Gündogan,Manchester City,M,28,13,7,50,5.97,6,0,19
9,Alexandre Lacazette,Arsenal,F,29,13,4,22,3.56,1,0,76
10,Callum Wilson,Newcastle United,F,16,12,1,50,8.50,2,0,66
11,Danny Ings,Southampton,F,28,12,4,69,14.60,6,0,44
12,Marcus Rashford,Manchester United,F,37,11,11,70,9.80,2,0,57
13,Sadio Mané,Liverpool,F,34,11,7,68,10.24,2,0,28
14,Gareth Bale,Tottenham,F,20,11,3,41,12.70,7,0,30
15,Phil Foden,Manchester City,M,28,9,5,28,6.50,4,1,64
16,Kevin De Bruyne,Manchester City,M,24,6,11,79,9.91,3,1,45
17,Jack Grealish,Aston Villa,F M S,26,6,10,50,5.19,7,0,33
18,Mason Greenwood,Manchester United,F,24,7,3,40,7.20,7,1,19
19,Timo Werner,Chelsea,F,35,6,4,80,13.43,2,1,49
20,Pierre-Emerick Aubameyang,Arsenal,F,29,10,3,50,10.30,5,1,69
21,Raheem Sterling,Manchester City,M S,33,10,5,44,8.44,4,1,75
22,Jesse Lingard,Manchester United,M,26,9,4,35,6.80,1,0,13
23,Riyad Mahrez,Manchester City,M S,33,9,5,56,9.50,7,1,5
24,Harvey Barnes,Leicester,F M S,34,9,4,60,10.40,3,0,12
25,Diogo Jota,Liverpool,F,30,9,4,58,8.60,5,1,67
26,Gabriel Jesus,Manchester City,F,26,8,4,52,7.80,5,1,15
27,Stuart Dallas,Leeds,D M S,37,8,2,26,5.10,1,1,12
28,Neal Maupay,Brighton,F M S,29,8,5,48,7.50,7,0,39
29,Nicolas Pepe,Arsenal,M S,33,8,3,58,7.20,3,1,39
30,Jarrod Bowen,West Ham,F M S,26,8,4,44,5.80,4,0,37
31,Bertrand Traoré,Aston Villa,F M S,30,7,2,32,4.20,0,1,9
32,Jorginho,Chelsea,D M S,28,7,2,26,3.80,3,0,45
33,Rodrigo,Leeds,F M S,29,7,2,30,4.00,1,1,32
34,Richarlison,Everton,F M S,35,7,2,48,6.80,5,0,11
35,Ferrán Torres,Manchester City,F M S,25,7,2,40,4.00,4,0,77
36,Tammy Abraham,Chelsea,F,28,6,3,45,5.20,3,1,76
37,Gylfi Sigurdsson,Everton,M S,29,6,3,36,4.10,0,0,16
38,Danny Welbeck,Brighton,F,28,6,3,28,3.80,0,1,38
39,Joe Wilcock,Crystal Palace,M S,25,8,1,44,4.80,2,1,37
40,James Maddison,Leicester,M S,28,8,4,40,4.20,2,1,52
41,Jack Harrison,Leeds,D,32,8,3,38,3.50,6,1,27
42,Roberto Firmino,Liverpool,F,33,9,1,54,7.00,1,1,66
43,Anwar El Ghazi,Aston Villa,F,28,10,2,48,6.50,7,1,41
44,Tomas Soucek,West Ham,M S,37,10,3,58,7.80,3,1,48
45,Edinson Cavani,Manchester United,F,26,10,1,38,5.40,3,1,39
46,Che Adams,Southampton,F,31,9,2,32,5.20,7,1,69
47,James Ward-Prowse,Southampton,D M S,35,8,2,28,4.80,6,1,51
48,Michail Antonio,West Ham,F,28,10,4,40,6.40,5,1,7
49,Christian Benteke,Crystal Palace,F,29,10,1,34,5.80,5,0,5

## 4. Melihat Data Awal dan Akhir

Sesuai materi: **`head()`** untuk baris pertama, **`tail()`** untuk baris terakhir.

In [7]:
# 3 baris pertama
print('=== df.head(3) ===')
df.head(3)

=== df.head(3) ===

,player_name,team_title,position,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
0,Harry Kane,Tottenham,F,35,23,14,138,22.17,6,0,67
1,Mohamed Salah,Liverpool,F,37,22,5,76,20.25,3,1,22
2,Bruno Fernandes,Manchester United,M,37,18,12,121,16.02,4,0,48

In [8]:
# 7 baris terakhir
print('=== df.tail(7) ===')
df.tail(7)

=== df.tail(7) ===

,player_name,team_title,position,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
43,Anwar El Ghazi,Aston Villa,F,28,10,2,48,6.5,7,1,41
44,Tomas Soucek,West Ham,M S,37,10,3,58,7.8,3,1,48
45,Edinson Cavani,Manchester United,F,26,10,1,38,5.4,3,1,39
46,Che Adams,Southampton,F,31,9,2,32,5.2,7,1,69
47,James Ward-Prowse,Southampton,D M S,35,8,2,28,4.8,6,1,51
48,Michail Antonio,West Ham,F,28,10,4,40,6.4,5,1,7
49,Christian Benteke,Crystal Palace,F,29,10,1,34,5.8,5,0,5

## 5. Inspeksi Tipe Data Setiap Kolom

Sesuai materi: **`df.dtypes`** untuk melihat tipe data tiap kolom.

In [9]:
print('=== Tipe Data Setiap Kolom ===')
print(df.dtypes)
print('\n💡 Keterangan:')
print('  - int64   = bilangan bulat (integer)')
print('  - float64 = bilangan desimal (float)')
print('  - object  = teks / string (categorical)')

=== Tipe Data Setiap Kolom ===
player_name      object
team_title       object
position         object
games             int64
goals             int64
assists           int64
shots             int64
xG              float64
yellow_cards      int64
red_cards         int64
key_passes        int64
dtype: object

💡 Keterangan:
  - int64   = bilangan bulat (integer)
  - float64 = bilangan desimal (float)
  - object  = teks / string (categorical)

## 6. Seleksi Kolom dari DataFrame

Sesuai materi: Membuang kolom ID yang tidak bermakna, mulai dari kolom **`player_name`** menggunakan **`df.iloc[:,:]`**

In [10]:
# Pilih semua kolom mulai dari player_name (semua kolom dalam kasus ini sudah bersih)
df_noid = df.copy()

# Alternatif: pilih kolom tertentu saja
kolom_penting = ['player_name', 'team_title', 'games', 'goals', 'assists', 'shots', 'xG', 'yellow_cards', 'red_cards']
df_noid = df[kolom_penting].copy()

print(f'DataFrame setelah seleksi kolom: {df_noid.shape}')
df_noid.head(5)

DataFrame setelah seleksi kolom: (50, 9)

,player_name,team_title,games,goals,assists,shots,xG,yellow_cards,red_cards
0,Harry Kane,Tottenham,35,23,14,138,22.17,6,0
1,Mohamed Salah,Liverpool,37,22,5,76,20.25,3,1
2,Bruno Fernandes,Manchester United,37,18,12,121,16.02,4,0
3,Son Heung-Min,Tottenham,37,17,10,68,11.02,6,1
4,Patrick Bamford,Leeds,38,17,7,82,18.40,2,0

## 7. Menampilkan Data dalam Urutan Tertentu

Sesuai materi: **`sort_values()`** untuk mengurutkan data.

In [11]:
# Sort berdasarkan player_name (ascending = A-Z)
df1 = df_noid.sort_values(by='player_name', ascending=True)
print('=== Sort by player_name (A-Z) — 10 baris pertama ===')
df1.head(10)

=== Sort by player_name (A-Z) — 10 baris pertama ===

,player_name,team_title,games,goals,assists,shots,xG,yellow_cards,red_cards
9,Alexandre Lacazette,Arsenal,29,13,4,22,3.56,1,0
43,Anwar El Ghazi,Aston Villa,28,10,2,48,6.50,7,1
31,Bertrand Traoré,Aston Villa,30,7,2,32,4.20,0,1
2,Bruno Fernandes,Manchester United,37,18,12,121,16.02,4,0
10,Callum Wilson,Newcastle United,16,12,1,50,8.50,2,0
46,Che Adams,Southampton,31,9,2,32,5.20,7,1
49,Christian Benteke,Crystal Palace,29,10,1,34,5.80,5,0
11,Danny Ings,Southampton,28,12,4,69,14.60,6,0
38,Danny Welbeck,Brighton,28,6,3,28,3.80,0,1
25,Diogo Jota,Liverpool,30,9,4,58,8.60,5,1

In [12]:
# Sort berdasarkan assists (descending), jika sama → sort by team_title (ascending)
df1 = df_noid.sort_values(
    by=['assists', 'team_title'],
    ascending=[False, True]
)
print('=== Sort by assists (DESC) lalu team_title (ASC) — 10 baris pertama ===')
df1.head(10)

=== Sort by assists (DESC) lalu team_title (ASC) — 10 baris pertama ===

,player_name,team_title,games,goals,assists,shots,xG,yellow_cards,red_cards
0,Harry Kane,Tottenham,35,23,14,138,22.17,6,0
2,Bruno Fernandes,Manchester United,37,18,12,121,16.02,4,0
16,Kevin De Bruyne,Manchester City,24,6,11,79,9.91,3,1
12,Marcus Rashford,Manchester United,37,11,11,70,9.80,2,0
17,Jack Grealish,Aston Villa,26,6,10,50,5.19,7,0
3,Son Heung-Min,Tottenham,37,17,10,68,11.02,6,1
4,Patrick Bamford,Leeds,38,17,7,82,18.40,2,0
13,Sadio Mané,Liverpool,34,11,7,68,10.24,2,0
8,Ilkay Gündogan,Manchester City,28,13,7,50,5.97,6,0
28,Neal Maupay,Brighton,29,8,5,48,7.50,7,0

In [13]:
# Sort berdasarkan goals terbanyak
df_top_scorer = df_noid.sort_values(by='goals', ascending=False)
print('=== Top 10 Pencetak Gol Terbanyak ===')
df_top_scorer[['player_name', 'team_title', 'goals', 'assists']].head(10)

=== Top 10 Pencetak Gol Terbanyak ===

             player_name         team_title  goals  assists
0             Harry Kane          Tottenham     23       14
1          Mohamed Salah          Liverpool     22        5
2        Bruno Fernandes  Manchester United     18       12
3          Son Heung-Min          Tottenham     17       10
4        Patrick Bamford              Leeds     17        7
5  Dominic Calvert-Lewin            Everton     16        4
6            Jamie Vardy          Leicester     15        4
7          Ollie Watkins        Aston Villa     14        4
8         Ilkay Gündogan    Manchester City     13        7
9    Alexandre Lacazette            Arsenal     13        4

## 8. Ringkasan

| Fungsi | Kegunaan |
|---|---|
| `pd.read_csv(path)` | Import file CSV ke DataFrame |
| `df.head(n)` | Tampilkan n baris pertama |
| `df.tail(n)` | Tampilkan n baris terakhir |
| `df.dtypes` | Cek tipe data tiap kolom |
| `df.iloc[:, n:]` | Pilih kolom dari index ke-n |
| `df[['col1','col2']]` | Pilih kolom tertentu |
| `df.sort_values(by=...)` | Urutkan data berdasarkan kolom |

> 💾 Dataset `epl_goalscorer_2021.csv` tersimpan di folder yang sama, akan dipakai oleh notebook selanjutnya.