# 📊 Notebook 2: Statistical Methods — Central Tendency & Distribution

**Topik:** `describe()`, Mean, Median, Mode, Range, Quantile, Std Dev, Variance, Outliers

---

## 0. Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset dari Notebook 1
path = 'epl_goalscorer_2021.csv'
df = pd.read_csv(path)

# Buat df_noid (tanpa kolom teks yang tidak perlu untuk statistik)
df_noid = df.copy()

print('✅ Dataset dimuat!')
print(f'Shape: {df_noid.shape}')
df_noid.head(3)

✅ Dataset dimuat!
Shape: (50, 11)

,player_name,team_title,position,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
0,Harry Kane,Tottenham,F,35,23,14,138,22.17,6,0,67
1,Mohamed Salah,Liverpool,F,37,22,5,76,20.25,3,1,22
2,Bruno Fernandes,Manchester United,M,37,18,12,121,16.02,4,0,48

---
## 1. Statistical Summary dengan `describe()`

Sesuai materi: `describe()` menampilkan count, mean, std, min, 25%, 50% (median), 75%, max.

In [2]:
# Statistik untuk kolom numerik saja
print('=== df_noid.describe() ===')
df_noid.describe()

=== df_noid.describe() ===

,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
count,50.000000,50.00000,50.000000,50.000000,50.000000,50.00000,50.000000,50.00000
mean,30.380000,10.16000,4.320000,52.560000,8.582800,3.86000,0.580000,40.96000
std,4.852477,3.97112,3.033419,22.907231,4.743605,2.16663,0.498569,22.30856
min,16.000000,6.00000,1.000000,22.000000,3.500000,0.00000,0.000000,5.00000
25%,28.000000,8.00000,2.000000,38.000000,5.192500,2.00000,0.000000,19.75000
50%,29.000000,9.00000,4.000000,48.000000,7.100000,4.00000,1.000000,39.00000
75%,34.750000,11.00000,5.000000,65.250000,10.285000,6.00000,1.000000,62.25000
max,38.000000,23.00000,14.000000,138.000000,22.170000,7.00000,1.000000,78.00000

In [3]:
# Termasuk kolom non-numerik (object)
print('=== df_noid.describe(include="all") ===')
print('👆 Kolom non-numerik akan memiliki: unique, top (mode), freq')
df_noid.describe(include='all')

=== df_noid.describe(include="all") ===
👆 Kolom non-numerik akan memiliki: unique, top (mode), freq

,player_name,team_title,position,games,goals,assists,shots,xG,yellow_cards,red_cards,key_passes
count,50,50,50,50.000000,50.00000,50.000000,50.000000,50.000000,50.00000,50.000000,50.00000
unique,50,15,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Harry Kane,Manchester City,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,7,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,30.380000,10.16000,4.320000,52.560000,8.582800,3.86000,0.580000,40.96000
std,NaN,NaN,NaN,4.852477,3.97112,3.033419,22.907231,4.743605,2.16663,0.498569,22.30856
min,NaN,NaN,NaN,16.000000,6.00000,1.000000,22.000000,3.500000,0.00000,0.000000,5.00000
25%,NaN,NaN,NaN,28.000000,8.00000,2.000000,38.000000,5.192500,2.00000,0.000000,19.75000
50%,NaN,NaN,NaN,29.000000,9.00000,4.000000,48.000000,7.100000,4.00000,1.000000,39.00000
75%,NaN,NaN,NaN,34.750000,11.00000,5.000000,65.250000,10.285000,6.00000,1.000000,62.25000
max,NaN,NaN,NaN,38.000000,23.00000,14.000000,138.000000,22.170000,7.00000,1.000000,78.00000

---
## 2. Central Tendency — Arithmetic Mean (Rata-rata)

**Definisi:** Jumlah semua nilai dibagi jumlah data.

$$\bar{x} = \frac{1}{N} \sum_{i=1}^{N} x_i$$

Sesuai materi: gunakan **`mean()`** di Pandas.

In [4]:
# Mean goals, games, assists, shots
mean_result = df_noid[['goals', 'games', 'assists', 'shots']].mean()
print('=== Rata-rata (Mean) ===')
print(mean_result)
print()
print(f'🔍 Interpretasi:')
print(f'  Rata-rata gol per pemain  : {mean_result["goals"]:.2f}')
print(f'  Rata-rata pertandingan    : {mean_result["games"]:.2f}')
print(f'  Rata-rata assist          : {mean_result["assists"]:.2f}')
print(f'  Rata-rata shots           : {mean_result["shots"]:.2f}')

=== Rata-rata (Mean) ===
goals      10.16
games      30.38
assists     4.32
shots      52.56
dtype: float64

🔍 Interpretasi:
  Rata-rata gol per pemain  : 10.16
  Rata-rata pertandingan    : 30.38
  Rata-rata assist          : 4.32
  Rata-rata shots           : 52.56

In [5]:
# Verifikasi manual untuk goals
total_goals = df_noid['goals'].sum()
n_players = len(df_noid)
mean_manual = total_goals / n_players
print(f'Total gol semua pemain : {total_goals}')
print(f'Jumlah pemain          : {n_players}')
print(f'Mean manual (total/n)  : {mean_manual:.4f}')
print(f'Mean via pandas        : {df_noid["goals"].mean():.4f}')
print(f'✅ Hasil sama!' if abs(mean_manual - df_noid['goals'].mean()) < 0.0001 else '❌ Berbeda!')

Total gol semua pemain : 508
Jumlah pemain          : 50
Mean manual (total/n)  : 10.1600
Mean via pandas        : 10.1600
✅ Hasil sama!

---
## 3. Central Tendency — Median

**Definisi:** Nilai tengah setelah data diurutkan. Lebih tahan terhadap outlier dibanding mean.

- Jika N **ganjil** → nilai di posisi (N+1)/2
- Jika N **genap** → rata-rata dua nilai tengah

Sesuai materi: gunakan **`median()`**

In [6]:
# Median goals, games, assists, shots
median_result = df_noid[['goals', 'games', 'assists', 'shots']].median()
print('=== Median ===')
print(median_result)

=== Median ===
goals       9.0
games      29.0
assists     4.0
shots      48.0
dtype: float64

In [7]:
# Perbandingan Mean vs Median (penting untuk cek skewness distribusi)
print('=== Perbandingan Mean vs Median ===')
comparison = pd.DataFrame({
    'Mean'  : df_noid[['goals','games','assists','shots']].mean(),
    'Median': df_noid[['goals','games','assists','shots']].median(),
})
comparison['Mean > Median?'] = comparison['Mean'] > comparison['Median']
comparison['Keterangan'] = comparison['Mean > Median?'].map(
    {True: '📈 Right-skewed (positif)', False: '📉 Left-skewed / Simetris'}
)
print(comparison)

=== Perbandingan Mean vs Median ===
          Mean  Median  Mean > Median?                Keterangan
goals    10.16     9.0            True  📈 Right-skewed (positif)
games    30.38    29.0            True  📈 Right-skewed (positif)
assists   4.32     4.0            True  📈 Right-skewed (positif)
shots    52.56    48.0            True  📈 Right-skewed (positif)

---
## 4. Central Tendency — Mode

**Definisi:** Nilai yang paling sering muncul. Bisa lebih dari satu.

Sesuai materi: Digunakan untuk data **nominal/kategorikal**. Gunakan **`mode()`**

In [8]:
# Mode dari kolom team_title (tim yang paling banyak punya pemain)
print('=== Mode team_title (Tim dengan pemain terbanyak) ===')
mode_team = df_noid[['team_title']].mode()
print(mode_team)
print()
print('=== Frekuensi tiap tim (value_counts) ===')
print(df_noid['team_title'].value_counts().head(10))

=== Mode team_title (Tim dengan pemain terbanyak) ===
        team_title
0  Manchester City

=== Frekuensi tiap tim (value_counts) ===
team_title
Manchester City      7
Manchester United    5
Liverpool            4
Aston Villa          4
Leeds                4
Everton              3
Tottenham            3
Leicester            3
Arsenal              3
Southampton          3
Name: count, dtype: int64

In [9]:
# Mode untuk data numerik (goals)
mode_goals = df_noid[['goals']].mode()
print('=== Mode goals (nilai gol yang paling sering muncul) ===')
print(mode_goals)
print()
print('Distribusi nilai goals:')
print(df_noid['goals'].value_counts().sort_index())

=== Mode goals (nilai gol yang paling sering muncul) ===
   goals
0      8

Distribusi nilai goals:
goals
6     6
7     6
8     9
9     7
10    7
11    3
12    2
13    2
14    1
15    1
16    1
17    2
18    1
22    1
23    1
Name: count, dtype: int64

---
## 5. Distribution — Range

**Definisi:** Selisih antara nilai maksimum dan minimum.

> ⚠️ Range sensitif terhadap outlier karena hanya bergantung pada 2 nilai ekstrim.

In [10]:
# Tidak ada fungsi range() khusus di Pandas, gunakan max() - min()
cols = ['goals', 'games', 'assists', 'shots']
print('=== Range (Max - Min) ===')
for col in cols:
    min_val = df_noid[col].min()
    max_val = df_noid[col].max()
    range_val = max_val - min_val
    print(f'{col:10s}: min={min_val:4}, max={max_val:4}, range={range_val:4}')

=== Range (Max - Min) ===
goals     : min=   6, max=  23, range=  17
games     : min=  16, max=  38, range=  22
assists   : min=   1, max=  14, range=  13
shots     : min=  22, max= 138, range= 116

---
## 6. Distribution — Quantiles & Quartiles

**Definisi:**
- Q1 (25%) → 25% data berada di bawah nilai ini
- Q2 / Median (50%) → nilai tengah
- Q3 (75%) → 75% data berada di bawah nilai ini

Sesuai materi: gunakan **`quantile(q=...)`**

In [11]:
# Q3 dari semua kolom numerik
print('=== Kuartil ke-3 (Q3 = 75%) semua kolom numerik ===')
df_noid.select_dtypes(include='number').quantile(0.75)

=== Kuartil ke-3 (Q3 = 75%) semua kolom numerik ===

games           34.750
goals           11.000
assists          5.000
shots           65.250
xG              10.285
yellow_cards     6.000
red_cards        1.000
key_passes      62.250
Name: 0.75, dtype: float64

In [12]:
# Q3 dari kolom goals saja
q3_goals = df_noid[['goals']].quantile(q=0.75)
print('=== Q3 goals ===')
print(q3_goals)

print()
print('=== Semua Quartile untuk goals ===')
for q_label, q_val in [('Q1 (25%)', 0.25), ('Q2/Median (50%)', 0.50), ('Q3 (75%)', 0.75)]:
    val = df_noid['goals'].quantile(q=q_val)
    print(f'  {q_label}: {val}')

=== Q3 goals ===
goals    11.0
Name: 0.75, dtype: float64

=== Semua Quartile untuk goals ===
  Q1 (25%): 8.0
  Q2/Median (50%): 9.0
  Q3 (75%): 11.0

In [13]:
# Tabel lengkap Q1, Q2, Q3 untuk semua kolom numerik
numeric_cols = df_noid.select_dtypes(include='number').columns
quartile_df = pd.DataFrame({
    'Q1 (25%)': df_noid[numeric_cols].quantile(0.25),
    'Q2/Median': df_noid[numeric_cols].quantile(0.50),
    'Q3 (75%)': df_noid[numeric_cols].quantile(0.75),
    'IQR (Q3-Q1)': df_noid[numeric_cols].quantile(0.75) - df_noid[numeric_cols].quantile(0.25),
})
print('=== Rangkuman Quartile ===')
quartile_df

=== Rangkuman Quartile ===

              Q1 (25%)  Q2/Median  Q3 (75%)  IQR (Q3-Q1)
games          28.0000       29.0    34.750       6.7500
goals           8.0000        9.0    11.000       3.0000
assists         2.0000        4.0     5.000       3.0000
shots          38.0000       48.0    65.250      27.2500
xG              5.1925        7.1    10.285       5.0925
yellow_cards    2.0000        4.0     6.000       4.0000
red_cards       0.0000        1.0     1.000       1.0000
key_passes     19.7500       39.0    62.250      42.5000

---
## 7. Distribution — Standard Deviation & Variance

**Definisi:**
$$s = \sqrt{\frac{\sum_{i=1}^{N}(x_i - \bar{x})^2}{N-1}}$$

- **Std Dev besar** → data menyebar jauh dari mean
- **Std Dev kecil** → data berkumpul dekat mean
- **Variance** = std dev²

In [14]:
# Variance dan Std Dev untuk goals
var_goals = df_noid[['goals']].var()
std_goals = df_noid[['goals']].std()

print(f'=== Variance dan Std Dev untuk goals ===')
print(f'Variance  : {var_goals["goals"]:.4f}')
print(f'Std Dev   : {std_goals["goals"]:.4f}')
print(f'Mean      : {df_noid["goals"].mean():.4f}')
print()
print(f'💡 Kebanyakan pemain mencetak gol dalam rentang:')
mean_g = df_noid['goals'].mean()
std_g = df_noid['goals'].std()
print(f'   [{mean_g - std_g:.1f}, {mean_g + std_g:.1f}] (±1σ)')

=== Variance dan Std Dev untuk goals ===
Variance  : 15.7698
Std Dev   : 3.9711
Mean      : 10.1600

💡 Kebanyakan pemain mencetak gol dalam rentang:
   [6.2, 14.1] (±1σ)

In [15]:
# Ringkasan statistik lengkap untuk goals
print('=== Ringkasan Lengkap Distribusi Goals ===')
stats_goals = {
    'Count'   : df_noid['goals'].count(),
    'Mean'    : df_noid['goals'].mean(),
    'Median'  : df_noid['goals'].median(),
    'Std Dev' : df_noid['goals'].std(),
    'Variance': df_noid['goals'].var(),
    'Min'     : df_noid['goals'].min(),
    'Max'     : df_noid['goals'].max(),
    'Range'   : df_noid['goals'].max() - df_noid['goals'].min(),
    'Q1'      : df_noid['goals'].quantile(0.25),
    'Q3'      : df_noid['goals'].quantile(0.75),
    'IQR'     : df_noid['goals'].quantile(0.75) - df_noid['goals'].quantile(0.25),
}
for k, v in stats_goals.items():
    print(f'  {k:10s}: {v:.4f}')

=== Ringkasan Lengkap Distribusi Goals ===
  Count     : 50.0000
  Mean      : 10.1600
  Median    : 9.0000
  Std Dev   : 3.9711
  Variance  : 15.7698
  Min       : 6.0000
  Max       : 23.0000
  Range     : 17.0000
  Q1        : 8.0000
  Q3        : 11.0000
  IQR       : 3.0000

---
## 8. Outliers — Metode 3-Sigma Rule

Sesuai materi: data disebut **outlier** jika jaraknya lebih dari 3× std dev dari mean.

- Outlier jika: $x_i < \bar{x} - 3\sigma$ atau $x_i > \bar{x} + 3\sigma$
- Probabilitas: hanya **0.27%** data yang wajar berada di luar ±3σ

In [16]:
# Deteksi outlier dengan 3-Sigma Rule pada kolom goals
mean_g = df_noid['goals'].mean()
std_g  = df_noid['goals'].std()

iso = (df_noid['goals'] < mean_g - 3*std_g) | (df_noid['goals'] > mean_g + 3*std_g)

df1 = df_noid[['player_name', 'goals']].assign(is_outlier=iso)

print(f'Mean  : {mean_g:.4f}')
print(f'StdDev: {std_g:.4f}')
print(f'Batas bawah  (μ - 3σ): {mean_g - 3*std_g:.2f}')
print(f'Batas atas   (μ + 3σ): {mean_g + 3*std_g:.2f}')
print()
print('=== Pemain yang teridentifikasi sebagai Outlier (3-Sigma) ===')
print(df1.loc[df1['is_outlier']])
print(f'\nTotal outlier: {iso.sum()} dari {len(df_noid)} pemain')

Mean  : 10.1600
StdDev: 3.9711
Batas bawah  (μ - 3σ): -1.75
Batas atas   (μ + 3σ): 22.07

=== Pemain yang teridentifikasi sebagai Outlier (3-Sigma) ===
  player_name  goals  is_outlier
0  Harry Kane     23        True

Total outlier: 1 dari 50 pemain

---
## 9. Outliers — Tukey's Fences (IQR Method)

Sesuai materi:
- **Outlier biasa** jika: $x_i < Q1 - 1.5 \times IQR$ atau $x_i > Q3 + 1.5 \times IQR$
- **Extreme outlier** jika: $x_i < Q1 - 3 \times IQR$ atau $x_i > Q3 + 3 \times IQR$

In [17]:
# Tukey's Fences untuk goals
q1  = df_noid['goals'].quantile(q=0.25)
q3  = df_noid['goals'].quantile(q=0.75)
iqr = q3 - q1

iso  = (df_noid['goals'] < q1 - 1.5*iqr) | (df_noid['goals'] > q3 + 1.5*iqr)
iseo = (df_noid['goals'] < q1 - 3*iqr)   | (df_noid['goals'] > q3 + 3*iqr)

df1 = df_noid[['player_name', 'goals']].assign(
    is_outlier=iso,
    is_extreme_outlier=iseo
)

print(f'Q1  : {q1}')
print(f'Q3  : {q3}')
print(f'IQR : {iqr}')
print(f'Batas outlier bawah  (Q1 - 1.5×IQR): {q1 - 1.5*iqr:.2f}')
print(f'Batas outlier atas   (Q3 + 1.5×IQR): {q3 + 1.5*iqr:.2f}')
print(f'Batas extreme bawah  (Q1 - 3×IQR)  : {q1 - 3*iqr:.2f}')
print(f'Batas extreme atas   (Q3 + 3×IQR)  : {q3 + 3*iqr:.2f}')
print()
print('=== Outlier & Extreme Outlier (Tukey) ===')
df1.loc[df1['is_outlier'] | df1['is_extreme_outlier']]

Q1  : 8.0
Q3  : 11.0
IQR : 3.0
Batas outlier bawah  (Q1 - 1.5×IQR): 3.50
Batas outlier atas   (Q3 + 1.5×IQR): 15.50
Batas extreme bawah  (Q1 - 3×IQR)  : -1.00
Batas extreme atas   (Q3 + 3×IQR)  : 20.00

=== Outlier & Extreme Outlier (Tukey) ===

             player_name  goals  is_outlier  is_extreme_outlier
0             Harry Kane     23        True                True
1          Mohamed Salah     22        True                True
2        Bruno Fernandes     18        True               False
3          Son Heung-Min     17        True               False
4        Patrick Bamford     17        True               False
5  Dominic Calvert-Lewin     16        True               False

---
## 10. Frequency Table & Grouping

Sesuai materi: **`value_counts()`** untuk melihat frekuensi data nominal.

In [18]:
# Frekuensi pemain per tim (value_counts)
print('=== Jumlah Pemain per Tim (value_counts) ===')
print(df_noid['team_title'].value_counts())
print()
print('💡 Nilai tertinggi = Mode dari kolom team_title')

=== Jumlah Pemain per Tim (value_counts) ===
team_title
Manchester City      7
Manchester United    5
Liverpool            4
Aston Villa          4
Leeds                4
Everton              3
Tottenham            3
Leicester            3
Arsenal              3
Southampton          3
Chelsea              3
West Ham             3
Brighton             2
Crystal Palace       2
Newcastle United     1
Name: count, dtype: int64

💡 Nilai tertinggi = Mode dari kolom team_title

In [19]:
# Groupby: rata-rata gol per tim (sesuai materi)
avg_goals_per_team = df_noid.groupby('team_title')[['goals']] \
    .mean() \
    .sort_values(by='goals', ascending=False)

print('=== Rata-rata Gol per Pemain untuk setiap Tim ===')
avg_goals_per_team

=== Rata-rata Gol per Pemain untuk setiap Tim ===

                       goals
team_title
Tottenham          17.000000
Liverpool          12.750000
Newcastle United   12.000000
Manchester United  11.000000
Leicester          10.666667
Arsenal            10.333333
Leeds              10.000000
Everton             9.666667
Southampton         9.666667
West Ham            9.333333
Aston Villa         9.250000
Crystal Palace      9.000000
Manchester City     8.857143
Brighton            7.000000
Chelsea             6.333333

---
## 11. Ringkasan Fungsi Statistik Pandas

| Fungsi | Kegunaan |
|---|---|
| `df.describe()` | Statistik dasar semua kolom numerik |
| `df.describe(include='all')` | Termasuk kolom kategorik |
| `df.mean()` | Rata-rata aritmatik |
| `df.median()` | Nilai tengah |
| `df.mode()` | Nilai yang paling sering muncul |
| `df.min()` / `df.max()` | Nilai minimum / maksimum |
| `df.quantile(q)` | Nilai kuantil ke-q (0–1) |
| `df.std()` | Standar deviasi |
| `df.var()` | Varians |
| `df.value_counts()` | Frekuensi tiap nilai unik |
| `df.groupby().mean()` | Rata-rata per grup |